import type { ApiEndpoint } from "./types";

export const apiEndpoints: ApiEndpoint[] = [
  { area: "Authentication", method: "POST", url: "/api/v1/auth/login", request: "{ username, password, unitId? }", response: "{ accessToken, refreshToken, employee, permissions, unitScope }", validation: ["username/password required", "unitId must be assigned to employee"], errors: ["401 invalid credentials", "403 inactive employee or unit"], status: [200, 401, 403, 429], security: "Rate limited, audited, password never logged." },
  { area: "Authorization", method: "GET", url: "/api/v1/auth/me", request: "JWT", response: "{ employee, rank, designation, unit, permissions }", validation: ["valid access token"], errors: ["401 expired token"], status: [200, 401], security: "JWT and token revocation check." },
  { area: "Upload", method: "POST", url: "/api/v1/documents", request: "multipart file plus { documentType, caseHints, policeStationId }", response: "{ documentId, virusScanStatus, ocrJobId }", validation: ["allowed MIME", "max file size", "station in caller scope", "checksum duplicate check"], errors: ["400 invalid metadata", "409 duplicate checksum", "415 unsupported media", "422 virus scan failed"], status: [201, 400, 409, 415, 422], security: "JWT, upload permission, malware scan, encrypted storage." },
  { area: "OCR", method: "POST", url: "/api/v1/documents/{documentId}/ocr", request: "{ force?: boolean }", response: "{ ocrResultId, status }", validation: ["document exists", "caller can access document"], errors: ["404 document not found", "409 OCR already running"], status: [202, 404, 409], security: "JWT and document process permission." },
  { area: "OCR", method: "GET", url: "/api/v1/documents/{documentId}/extractions", request: "path documentId", response: "{ document, ocrResults, extractionLogs, proposedCasePatch }", validation: ["documentId UUID"], errors: ["404 document not found"], status: [200, 404], security: "PII filtered by permission; prompt-injection findings visible to reviewers." },
  { area: "Case", method: "POST", url: "/api/v1/cases", request: "{ caseMaster, complainants, victims, accused, actSections, arrests?, chargesheets?, sourceExtractionId? }", response: "{ caseMasterId, crimeNo, caseNo, version }", validation: ["required CaseMaster fields", "valid FK lookups", "active act-section pairs", "coordinate bounds"], errors: ["400 malformed", "403 scope denied", "409 duplicate CrimeNo", "422 legal validation failed"], status: [201, 400, 403, 409, 422], security: "JWT, case:create, audit, transaction, idempotency key." },
  { area: "Case", method: "GET", url: "/api/v1/cases/{caseMasterId}", request: "path caseMasterId", response: "{ caseMaster, complainants, victims, accused, actSections, arrests, chargesheets, predictions, alerts }", validation: ["caseMasterId integer"], errors: ["404 case not found"], status: [200, 404], security: "JWT, case read permission, jurisdiction filter, PII masking." },
  { area: "Case", method: "PATCH", url: "/api/v1/cases/{caseMasterId}", request: "{ version, patch, reason }", response: "{ caseMasterId, version, changedTables }", validation: ["version required", "reason for sensitive fields", "FKs active"], errors: ["409 version conflict", "422 validation failed"], status: [200, 409, 422], security: "JWT, case:update, audit/history, outbox event." },
  { area: "Victim", method: "POST", url: "/api/v1/cases/{caseMasterId}/victims", request: "{ victimName, ageYear, genderId, victimPolice }", response: "{ victimMasterId }", validation: ["case exists", "ageYear >= 0", "gender valid"], errors: ["404 case not found", "422 invalid victim"], status: [201, 404, 422], security: "JWT, case:update, PII audit." },
  { area: "Accused", method: "POST", url: "/api/v1/cases/{caseMasterId}/accused", request: "{ accusedName, ageYear, genderId, personId }", response: "{ accusedMasterId, repeatOffenderCandidates }", validation: ["personId unique inside case", "ageYear >= 0"], errors: ["409 duplicate personId", "422 invalid accused"], status: [201, 409, 422], security: "JWT, case:update; repeat-offender candidates require elevated permission." },
  { area: "Chargesheet", method: "POST", url: "/api/v1/cases/{caseMasterId}/chargesheets", request: "{ csdate, cstype, policePersonId, documentId? }", response: "{ csid, caseStatus }", validation: ["cstype in A/B/C", "policePersonId valid", "case exists"], errors: ["404 case not found", "422 invalid chargesheet"], status: [201, 404, 422], security: "JWT, chargesheet:create, audit." },
  { area: "Knowledge Graph", method: "GET", url: "/api/v1/graph/cases/{caseMasterId}", request: "path caseMasterId, query depth", response: "{ nodes, edges, explanations }", validation: ["depth between 1 and 3"], errors: ["404 case not found"], status: [200, 404], security: "JWT, graph:read, PII masking and scope filtering." },
  { area: "Prediction", method: "POST", url: "/api/v1/predictions/hotspots:refresh", request: "{ districtId, unitId?, crimeHeadId?, windowStart, windowEnd }", response: "{ jobId, status }", validation: ["districtId valid", "windowStart before windowEnd"], errors: ["403 scope denied", "422 invalid window"], status: [202, 403, 422], security: "JWT, prediction:run." },
  { area: "Prediction", method: "GET", url: "/api/v1/predictions/hotspots", request: "query districtId, unitId?, crimeHeadId?, windowStart, windowEnd", response: "{ hotspots, modelVersion, generatedAt }", validation: ["valid district/unit scope"], errors: ["403 scope denied"], status: [200, 403], security: "JWT, prediction:read." },
  { area: "Simulation", method: "POST", url: "/api/v1/simulations", request: "{ districtId, unitId?, interventionType, inputs }", response: "{ scenarioId, status }", validation: ["supported intervention", "bounded inputs"], errors: ["422 invalid simulation inputs"], status: [202, 422], security: "JWT, simulation:run, audited." },
  { area: "Dashboard", method: "GET", url: "/api/v1/dashboard/overview", request: "query districtId?, unitId?, dateRange", response: "{ caseCounts, hotspots, alerts, graphStats, recommendations }", validation: ["scope in caller jurisdiction", "date range limit"], errors: ["403 scope denied"], status: [200, 403], security: "JWT, dashboard:read; cached by scope and version." },
  { area: "Alert", method: "GET", url: "/api/v1/alerts", request: "query status?, severity?, districtId?, unitId?", response: "{ items, nextCursor }", validation: ["cursor valid", "scope valid"], errors: ["403 scope denied"], status: [200, 403], security: "JWT, alert:read." },
  { area: "Alert", method: "PATCH", url: "/api/v1/alerts/{alertId}", request: "{ status, note? }", response: "{ alertId, status }", validation: ["status transition allowed"], errors: ["404 alert not found", "409 invalid transition"], status: [200, 404, 409], security: "JWT, alert:update, audit." },
  { area: "Analytics", method: "GET", url: "/api/v1/analytics/crime-trends", request: "query districtId?, unitId?, crimeHeadId?, bucket=day|week|month", response: "{ series, dimensions, generatedAt }", validation: ["bucket allowed", "date range bounded"], errors: ["422 range too large"], status: [200, 422], security: "JWT, analytics:read; aggregate-only for lower roles." },
  { area: "Admin", method: "GET", url: "/api/v1/admin/lookups/{lookupName}", request: "path lookupName", response: "{ items }", validation: ["lookupName allowlisted"], errors: ["404 lookup not found"], status: [200, 404], security: "JWT, admin or lookup read permission." }
];
